### ISSUE TITLE
searching sometimes unexpectedly stops working

### ISSUE THREAD

**Issue by h3oCharles** [yadPe/beatconnect_client#274]
when i recieved a dev build, i managed to get some error logs

![unknown](https://user-images.githubusercontent.com/8020330/103583185-963a2a80-4edf-11eb-9eeb-26b0c4dd07c8.png)
![unknown](https://user-images.githubusercontent.com/8020330/103583212-a2be8300-4edf-11eb-8998-5f5f4a19bbd6.png)
![unknown](https://user-images.githubusercontent.com/8020330/103583232-aa7e2780-4edf-11eb-9afa-d500b4156cdb.png)

**Comment by yadPe** [comment]
Unable to reproduce after https://github.com/yadPe/beatconnect_client/pull/275 might have fixed it
Please reopen if problem still exist
